version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      stackton:
        aliases:
          - americachip.test

  database:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql8.0
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - stackton

  php7.4:
    extends:
      file: php-service.yml
      service: php
    build:
      args:
        PHP_VERSION: "7.4"
        XDEBUG_VERSION: "3.1.4"
    image: gerbton/php7.4-xdebug-node
    container_name: php7.4

  php8.0:
    extends:
      file: php-service.yml
      service: php
    build:
      args:
        PHP_VERSION: "8.0"
    image: gerbton/php8.0-xdebug-node
    container_name: php8.0

  php8.2:
    extends:
      file: php-service.yml
      service: php
    build:
      args:
        PHP_VERSION: "8.2"
    image: gerbton/php8.2-xdebug-node
    container_name: php8.2

  mailhog:
    container_name: mailhog
    platform: linux/x86_64
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - stackton

  redis:
    container_name: redis
    platform: linux/x86_64
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - stackton

networks:
  stackton:
    external: true
