version: '3'
services:
  php:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        NODE_VERSION: 18
        PHP_VERSION: ${PHP_VERSION:-8.2}
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      MAILHOG_HOST: mailhog
      MAILHOG_PORT: 1025
      MAILHOG_SEND: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./www:/var/www
      - ./php/conf.d/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./php/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - stackton
